### ISSUE TITLE
maybe have a way to nominate a step to receive standard input

### ISSUE THREAD

**Issue by silky** [sordina/logody#3]
for example maybe one of them is a python program, and you want to be able to enter debug mode.

**Comment by sordina** [comment]
@silky could you add more details to the example? Couldn't this be done with the script type? Or is there something else required?

**Comment by silky** [comment]
weird; you're right, it just works

at least, it just works in the little example i have; i think something weird is happening with flask when i try and do it there, but :shrug:

thanks!
